php -m |grep ctype 
php -m |grep curl 
php -m |grep dom 
php -m |grep fileinfo 
php -m |grep filter 
php -m |grep hash 
php -m |grep mbstring 
php -m |grep openssl 
php -m |grep pcre 
php -m |grep pdo 
php -m |grep session 
php -m |grep tokenizer 
php -m |grep xml 